const webhookPayload = {
  backup_code_enabled: false,
  banned: false,
  create_organization_enabled: true,
  created_at: 1748597278284,
  delete_self_enabled: true,
  email_addresses: [
    {
      created_at: 1748597251794,
      email_address: "addyyy118@gmail.com",
      id: "idn_2xoGwbwWVxxO4yKaMjrPEDWVMVE",
      linked_to: [Array],
      matches_sso_connection: false,
      object: "email_address",
      reserved: false,
      updated_at: 1748597278299,
      verification: [Object],
    },
  ],
  enterprise_accounts: [],
  external_accounts: [
    {
      approved_scopes:
        "email https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid profile",
      avatar_url:
        "https://lh3.googleusercontent.com/a/ACg8ocLCHc4RF1AMWFU1KUiZEwfjiXCdENj4wPaPkRmR89UUeW1Nsw22=s1000-c",
      created_at: 1748597251788,
      email_address: "addyyy118@gmail.com",
      external_account_id: "eac_2xoGwV21Rj9NlXtDhCWvHbiDkP8",
      family_name: "",
      first_name: "Addy",
      given_name: "Addy",
      google_id: "115590993736424921300",
      id: "idn_2xoGwZtddwUAYzax9xwlSGlO2Ms",
      identification_id: "idn_2xoGwZtddwUAYzax9xwlSGlO2Ms",
      image_url:
        "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMQ0hjNFJGMUFNV0ZVMUtVaVpFd2ZqaVhDZEVOajR3UGFQa1JtUjg5VVVlVzFOc3cyMj1zMTAwMC1jIiwicyI6IklNOGozYmQ0a052aWR5UXd4aXU3aUlnZlNpRzN4eUZTUmNPc04wREwxbE0ifQ",
      label: null,
      last_name: "",
      object: "google_account",
      picture:
        "https://lh3.googleusercontent.com/a/ACg8ocLCHc4RF1AMWFU1KUiZEwfjiXCdENj4wPaPkRmR89UUeW1Nsw22=s1000-c",
      provider: "oauth_google",
      provider_user_id: "115590993736424921300",
      public_metadata: {},
      updated_at: 1748598762971,
      username: "",
      verification: [Object],
    },
  ],
  external_id: null,
  first_name: "Addy",
  has_image: true,

  // main clerk user id
  id: "user_2xoGzvT1nGA0JkLQBcotjQazvW7",

  image_url:
    "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18yeG9HenRIMGZ0SXpIZTdJeTRpU1dhVklXdnMifQ",
  last_active_at: 1748597278283,
  last_name: null,
  last_sign_in_at: 1748598762989,
  legal_accepted_at: null,
  locked: false,
  lockout_expires_in_seconds: null,
  mfa_disabled_at: null,
  mfa_enabled_at: null,
  object: "user",
  passkeys: [],
  password_enabled: false,
  phone_numbers: [
    {
      backup_codes: null,
      created_at: 1748597263980,
      default_second_factor: false,
      id: "idn_2xoGy6akoW7O4fEldQlcpG6AKoH",
      linked_to: [],
      object: "phone_number",
      phone_number: "+919082486599",
      reserved: false,
      reserved_for_second_factor: false,
      updated_at: 1748597278302,
      verification: [Object],
    },
  ],
  primary_email_address_id: "idn_2xoGwbwWVxxO4yKaMjrPEDWVMVE",
  primary_phone_number_id: "idn_2xoGy6akoW7O4fEldQlcpG6AKoH",
  primary_web3_wallet_id: null,
  private_metadata: {},
  profile_image_url:
    "https://images.clerk.dev/oauth_google/img_2xoGztH0ftIzHe7Iy4iSWaVIWvs",
  public_metadata: {},
  saml_accounts: [],
  totp_enabled: false,
  two_factor_enabled: false,
  unsafe_metadata: {},
  updated_at: 1748607195307,
  username: "addy118",
  verification_attempts_remaining: 100,
  web3_wallets: [],
};
