services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - 8080:80
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - server

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
