const clerkUser = {
  id: "user_2xr6Vz2hPcAvh0HmMGacSHaBwsm",
  pathRoot: "/me",
  externalId: null,
  username: "addy_118",
  emailAddresses: [
    {
      id: "idn_2xr6UgWVTOvmxnSXYemZqcKVQrs",
      pathRoot: "/me/email_addresses",
      emailAddress: "addyyy118@gmail.com",
      matchesSsoConnection: false,
      linkedTo: [
        {
          id: "idn_2xr6Umt1gcnMV6LpkcTkzfiY067",
          pathRoot: "",
          type: "oauth_google",
        },
      ],
      verification: {
        pathRoot: "",
        status: "verified",
        strategy: "from_oauth_google",
        nonce: null,
        message: null,
        externalVerificationRedirectURL: null,
        attempts: null,
        expireAt: "2025-05-31T10:33:40.358Z",
        error: null,
      },
    },
  ],
  phoneNumbers: [],
  web3Wallets: [],
  externalAccounts: [
    {
      id: "eac_2xr6UkVZ9Fft8oyiS9GaR64VYVT",
      pathRoot: "/me/external_accounts",
      identificationId: "idn_2xr6Umt1gcnMV6LpkcTkzfiY067",
      provider: "google",
      providerUserId: "115590993736424921300",
      emailAddress: "addyyy118@gmail.com",
      approvedScopes:
        "email https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid profile",
      firstName: "Addy",
      lastName: "",
      imageUrl:
        "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMQ0hjNFJGMUFNV0ZVMUtVaVpFd2ZqaVhDZEVOajR3UGFQa1JtUjg5VVVlVzFOc3cyMj1zMTAwMC1jIiwicyI6IklNOGozYmQ0a052aWR5UXd4aXU3aUlnZlNpRzN4eUZTUmNPc04wREwxbE0ifQ",
      username: null,
      phoneNumber: null,
      publicMetadata: {},
      label: null,
      verification: {
        pathRoot: "",
        status: "verified",
        strategy: "oauth_google",
        nonce: null,
        message: null,
        externalVerificationRedirectURL: null,
        attempts: null,
        expireAt: "2025-05-31T09:40:51.722Z",
        error: null,
      },
    },
  ],
  enterpriseAccounts: [],
  passkeys: [],
  samlAccounts: [],
  organizationMemberships: [],
  passwordEnabled: false,
  firstName: "Addy",
  lastName: "Kirti",
  fullName: "Addy Kirti",
  primaryEmailAddressId: "idn_2xr6UgWVTOvmxnSXYemZqcKVQrs",
  primaryEmailAddress: {
    id: "idn_2xr6UgWVTOvmxnSXYemZqcKVQrs",
    pathRoot: "/me/email_addresses",
    emailAddress: "addyyy118@gmail.com",
    matchesSsoConnection: false,
    linkedTo: [
      {
        id: "idn_2xr6Umt1gcnMV6LpkcTkzfiY067",
        pathRoot: "",
        type: "oauth_google",
      },
    ],
    verification: {
      pathRoot: "",
      status: "verified",
      strategy: "from_oauth_google",
      nonce: null,
      message: null,
      externalVerificationRedirectURL: null,
      attempts: null,
      expireAt: "2025-05-31T10:33:40.358Z",
      error: null,
    },
  },
  primaryPhoneNumberId: null,
  primaryPhoneNumber: null,
  primaryWeb3WalletId: null,
  primaryWeb3Wallet: null,
  imageUrl:
    "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18yeHI2VnZheVlFVDlLSzRyQ0djaTE5c0ZNV2QifQ",
  hasImage: true,
  twoFactorEnabled: false,
  totpEnabled: false,
  backupCodeEnabled: false,
  publicMetadata: {},
  unsafeMetadata: {},
  createOrganizationEnabled: true,
  createOrganizationsLimit: null,
  deleteSelfEnabled: true,
  lastSignInAt: "2025-05-31T09:31:12.582Z",
  legalAcceptedAt: null,
  updatedAt: "2025-05-31T09:31:12.597Z",
  createdAt: "2025-05-31T09:31:12.563Z",
  cachedSessionsWithActivities: null,
};
